nnoremap <nowait> <S-Esc> :echo "S-Esc"<CR>
nnoremap <nowait> ~ :echo "S-`"<CR>
nnoremap <nowait> ! :echo "S-1"<CR>
nnoremap <nowait> @ :echo "S-2"<CR>
nnoremap <nowait> # :echo "S-3"<CR>
nnoremap <nowait> $ :echo "S-4"<CR>
nnoremap <nowait> % :echo "S-5"<CR>
nnoremap <nowait> ^ :echo "S-6"<CR>
nnoremap <nowait> & :echo "S-7"<CR>
nnoremap <nowait> * :echo "S-8"<CR>
nnoremap <nowait> ( :echo "S-9"<CR>
nnoremap <nowait> ) :echo "S-0"<CR>
nnoremap <nowait> _ :echo "S--"<CR>
nnoremap <nowait> + :echo "S-="<CR>
nnoremap <nowait> <S-BS> :echo "S-BS"<CR>
nnoremap <nowait> <S-Tab> :echo "S-Tab"<CR>
nnoremap <nowait> Q :echo "S-q"<CR>
nnoremap <nowait> W :echo "S-w"<CR>
nnoremap <nowait> E :echo "S-e"<CR>
nnoremap <nowait> R :echo "S-r"<CR>
nnoremap <nowait> T :echo "S-t"<CR>
nnoremap <nowait> Y :echo "S-y"<CR>
nnoremap <nowait> U :echo "S-u"<CR>
nnoremap <nowait> I :echo "S-i"<CR>
nnoremap <nowait> O :echo "S-o"<CR>
nnoremap <nowait> P :echo "S-p"<CR>
nnoremap <nowait> { :echo "S-["<CR>
nnoremap <nowait> } :echo "S-]"<CR>
nnoremap <nowait> <Bar> :echo "S-\\"<CR>
nnoremap <nowait> A :echo "S-a"<CR>
nnoremap <nowait> S :echo "S-s"<CR>
nnoremap <nowait> D :echo "S-d"<CR>
nnoremap <nowait> F :echo "S-f"<CR>
nnoremap <nowait> G :echo "S-g"<CR>
nnoremap <nowait> H :echo "S-h"<CR>
nnoremap <nowait> J :echo "S-j"<CR>
nnoremap <nowait> K :echo "S-k"<CR>
nnoremap <nowait> L :echo "S-l"<CR>
nnoremap <nowait> : :echo "S-;"<CR>
nnoremap <nowait> " :echo "S-'"<CR>
nnoremap <nowait> <S-CR> :echo "S-CR"<CR>
nnoremap <nowait> Z :echo "S-z"<CR>
nnoremap <nowait> X :echo "S-x"<CR>
nnoremap <nowait> C :echo "S-c"<CR>
nnoremap <nowait> V :echo "S-v"<CR>
nnoremap <nowait> B :echo "S-b"<CR>
nnoremap <nowait> N :echo "S-n"<CR>
nnoremap <nowait> M :echo "S-m"<CR>
nnoremap <nowait> < :echo "S-,"<CR>
nnoremap <nowait> > :echo "S-."<CR>
nnoremap <nowait> ? :echo "S-/"<CR>

" NOTE: When <S-Space> is pressed, terminal emulators send <Space>
nnoremap <nowait> <S-Space> :echo "S-Space"<CR>

nnoremap <nowait> <S-Up> :echo "S-Up"<CR>
nnoremap <nowait> <S-Down> :echo "S-Down"<CR>
nnoremap <nowait> <S-Left> :echo "S-Left"<CR>
nnoremap <nowait> <S-Right> :echo "S-Right"<CR>
