imap <M-a> M-a<CR>
imap <M-b> M-b<CR>
imap <M-c> M-c<CR>
imap <M-d> M-d<CR>
imap <M-e> M-e<CR>
imap <M-f> M-f<CR>
imap <M-g> M-g<CR>
imap <M-h> M-h<CR>
imap <M-i> M-i<CR>
imap <M-j> M-j<CR>
imap <M-k> M-k<CR>
imap <M-l> M-l<CR>
imap <M-m> M-m<CR>
imap <M-n> M-n<CR>
imap <M-o> M-o<CR>
imap <M-p> M-p<CR>
imap <M-q> M-q<CR>
imap <M-r> M-r<CR>
imap <M-s> M-s<CR>
imap <M-t> M-t<CR>
imap <M-u> M-u<CR>
imap <M-v> M-v<CR>
imap <M-w> M-w<CR>
imap <M-x> M-x<CR>
imap <M-y> M-y<CR>
imap <M-z> M-z<CR>
imap <M-0> M-0<CR>
imap <M-1> M-1<CR>
imap <M-2> M-2<CR>
imap <M-3> M-3<CR>
imap <M-4> M-4<CR>
imap <M-5> M-5<CR>
imap <M-6> M-6<CR>
imap <M-7> M-7<CR>
imap <M-8> M-8<CR>
imap <M-9> M-9<CR>
imap <M-`> M-`<CR>
imap <M--> M--<CR>
imap <M-=> M-=<CR>
imap <M-[> M-[<CR>
imap <M-]> M-]<CR>
imap <M-\> M-\<CR>
imap <M-;> M-;<CR>
imap <M-'> M-'<CR>
imap <M-,> M-,<CR>
imap <M-.> M-.<CR>
imap <M-/> M-/<CR>
imap <M-CR> M-CR<CR>
imap <M-BS> M-BS<CR>
