inoremap <C-Esc> C-Esc<CR>
inoremap <C-`> C-`<CR>
inoremap <C-1> C-1<CR>
inoremap <C-2> C-2<CR>
inoremap <C-3> C-3<CR>
inoremap <C-4> C-4<CR>
inoremap <C-5> C-5<CR>
inoremap <C-6> C-6<CR>
inoremap <C-7> C-7<CR>
inoremap <C-8> C-8<CR>
inoremap <C-9> C-9<CR>
inoremap <C-0> C-0<CR>
inoremap <C--> C--<CR>
inoremap <C-=> C-=<CR>
inoremap <C-BS> C-BS<CR>
inoremap <C-Tab> C-Tab<CR>
inoremap <C-q> C-q<CR>
inoremap <C-w> C-w<CR>
inoremap <C-e> C-e<CR>
inoremap <C-r> C-r<CR>
inoremap <C-t> C-t<CR>
inoremap <C-y> C-y<CR>
inoremap <C-u> C-u<CR>
inoremap <C-i> C-i<CR>
inoremap <C-o> C-o<CR>
inoremap <C-p> C-p<CR>
inoremap <C-[> C-[<CR>
inoremap <C-]> C-]<CR>
inoremap <C-\> C-\<CR>
inoremap <C-a> C-a<CR>
inoremap <C-s> C-s<CR>
inoremap <C-d> C-d<CR>
inoremap <C-f> C-f<CR>
inoremap <C-g> C-g<CR>
inoremap <C-h> C-h<CR>
inoremap <C-j> C-j<CR>
inoremap <C-k> C-k<CR>
inoremap <C-l> C-l<CR>
inoremap <C-;> C-;<CR>
inoremap <C-'> C-'<CR>
inoremap <C-CR> C-CR<CR>
inoremap <C-z> C-z<CR>
inoremap <C-x> C-x<CR>
inoremap <C-c> C-c<CR>
inoremap <C-v> C-v<CR>
inoremap <C-b> C-b<CR>
inoremap <C-n> C-n<CR>
inoremap <C-m> C-m<CR>
inoremap <C-,> C-,<CR>
inoremap <C-.> C-.<CR>
inoremap <C-/> C-/<CR>
