nmap <M-a> :echo "a"<CR>
nmap <M-b> :echo "b"<CR>
nmap <M-c> :echo "c"<CR>
nmap <M-d> :echo "d"<CR>
nmap <M-e> :echo "e"<CR>
nmap <M-f> :echo "f"<CR>
nmap <M-g> :echo "g"<CR>
nmap <M-h> :echo "h"<CR>
nmap <M-i> :echo "i"<CR>
nmap <M-j> :echo "j"<CR>
nmap <M-k> :echo "k"<CR>
nmap <M-l> :echo "l"<CR>
nmap <M-m> :echo "m"<CR>
nmap <M-n> :echo "n"<CR>
nmap <M-o> :echo "o"<CR>
nmap <M-p> :echo "p"<CR>
nmap <M-q> :echo "q"<CR>
nmap <M-r> :echo "r"<CR>
nmap <M-s> :echo "s"<CR>
nmap <M-t> :echo "t"<CR>
nmap <M-u> :echo "u"<CR>
nmap <M-v> :echo "v"<CR>
nmap <M-w> :echo "w"<CR>
nmap <M-x> :echo "x"<CR>
nmap <M-y> :echo "y"<CR>
nmap <M-z> :echo "z"<CR>
nmap <M-0> :echo "0"<CR>
nmap <M-1> :echo "1"<CR>
nmap <M-2> :echo "2"<CR>
nmap <M-3> :echo "3"<CR>
nmap <M-4> :echo "4"<CR>
nmap <M-5> :echo "5"<CR>
nmap <M-6> :echo "6"<CR>
nmap <M-7> :echo "7"<CR>
nmap <M-8> :echo "8"<CR>
nmap <M-9> :echo "9"<CR>
nmap <M-`> :echo "`"<CR>
nmap <M--> :echo "-"<CR>
nmap <M-=> :echo "="<CR>
nmap <M-[> :echo "["<CR>
nmap <M-]> :echo "]"<CR>
nmap <M-\> :echo "\\"<CR>
nmap <M-;> :echo ";"<CR>
nmap <M-'> :echo "'"<CR>
nmap <M-,> :echo ","<CR>
nmap <M-.> :echo "."<CR>
nmap <M-/> :echo "/"<CR>
nmap <M-CR> :echo "CR"<CR>
nmap <M-BS> :echo "BS"<CR>
