" NOTE: <M-Esc> is reserved for "Speak Selection" at the OS level
" inoremap <M-Esc> M-Esc<CR>

inoremap <M-`> M-`<CR>
inoremap <M-1> M-1<CR>
inoremap <M-2> M-2<CR>
inoremap <M-3> M-3<CR>
inoremap <M-4> M-4<CR>
inoremap <M-5> M-5<CR>
inoremap <M-6> M-6<CR>
inoremap <M-7> M-7<CR>
inoremap <M-8> M-8<CR>
inoremap <M-9> M-9<CR>
inoremap <M-0> M-0<CR>
inoremap <M--> M--<CR>
inoremap <M-=> M-=<CR>
inoremap <M-BS> M-BS<CR>
inoremap <M-Tab> M-Tab<CR>
inoremap <M-q> M-q<CR>
inoremap <M-w> M-w<CR>
inoremap <M-e> M-e<CR>
inoremap <M-r> M-r<CR>
inoremap <M-t> M-t<CR>
inoremap <M-y> M-y<CR>
inoremap <M-u> M-u<CR>
inoremap <M-i> M-i<CR>
inoremap <M-o> M-o<CR>
inoremap <M-p> M-p<CR>
inoremap <M-[> M-[<CR>
inoremap <M-]> M-]<CR>
inoremap <M-\> M-\<CR>
inoremap <M-a> M-a<CR>
inoremap <M-s> M-s<CR>
inoremap <M-d> M-d<CR>
inoremap <M-f> M-f<CR>
inoremap <M-g> M-g<CR>
inoremap <M-h> M-h<CR>
inoremap <M-j> M-j<CR>
inoremap <M-k> M-k<CR>
inoremap <M-l> M-l<CR>
inoremap <M-;> M-;<CR>
inoremap <M-'> M-'<CR>
inoremap <M-CR> M-CR<CR>
inoremap <M-z> M-z<CR>
inoremap <M-x> M-x<CR>
inoremap <M-c> M-c<CR>
inoremap <M-v> M-v<CR>
inoremap <M-b> M-b<CR>
inoremap <M-n> M-n<CR>
inoremap <M-m> M-m<CR>
inoremap <M-,> M-,<CR>
inoremap <M-.> M-.<CR>
inoremap <M-/> M-/<CR>
inoremap <M-Space> M-Space<CR>
inoremap <M-Up> M-Up<CR>
inoremap <M-Down> M-Down<CR>
inoremap <M-Left> M-Left<CR>
inoremap <M-Right> M-Right<CR>
